### ISSUE TITLE
Example Geotag?

### ISSUE THREAD

**Issue by kaihendry** [garyhouston/exif44#1]
Would be nice to see an example of a JPEG being set with a GPS latitude/longitude information.

**Comment by garyhouston** [comment]
I'd like to do that, since as well as being a good example, I do it occasionally with Exiftool. As well as formatting the data into the right fields, there are various cases such as files with a GPS IFD already present, GPS IFD not present, and the entire Exif block not present.

**Comment by garyhouston** [comment]
I added exif44addloc, although it's a bit on the complex side. Some of the stuff its doing should probably be moved into library functions.
